puppetlabs/modulesync_configs

config_defaults.yml

No reason to test future parser on more than one ruby version. We don't *really* care about puppet 3.4.x...

Remove extra future parser and old puppet version tests

---

config_defaults.yml

Puppet 4 shipped with ruby 2.1.6 in puppet-agent 1.0.1, so we should
test with that.
Not a failing test yet.

Add puppet 4

---

moduleroot/CONTRIBUTING.md

Consistently use 'bundle exec' in examples of executing tests.

(MODULES-1885) update docs

---

config_defaults.yml
moduleroot/Gemfile

Further restrict down the restrictions on windows dependencies when using older
Puppet versions, such that it works with Puppet 3.0.0 - 3.7.0. It does require
a bit more logic in selecting gems but it allows for testing older platforms
without any additional known issues for Puppet versions under 3.4.0.

(MODULES-2207) Windows Gem file restrictions for Older puppet versions

---

config_defaults.yml
moduleroot/Gemfile

Ensure that beaker rspec is at least on a version that supports the
use of specinfra, and is not known to contain bugs.

(MODULES-2207) bin beaker-rspec to ~> 5.1

---

config_defaults.yml

* run rake once with all the targets instead of spawning it thrice
* enforce unit test on puppet 4
* add the metadata-json-lint gem to enable this validation

(maint) several fixes to the default config

---

README.md
moduleroot/.rspec
moduleroot/spec/spec.opts

These can still be overridden by setting SPEC_OPTS or on the commandline,
if required.
This supersedes #17 .

(maint) reactivate default rspec options

---

moduleroot/Gemfile

For Puppet older than 3.5.0 on Windows, a facter version at or under
1.7.5 should be selected for greatest compatibility when requesting
a gem puppet version and if a facter version has not been specified.

(maint) Guarantee Facter version for old Puppets - Windows

---

config_defaults.yml
managed_modules.yml

Prior to this PR:
motd module is not on the list of managed modules in managed_modules.yml 
gem master_manipulator is not in the list of gem in config_defaults.yml
This PR will add motd module into managed list of modulesync and add master_manipulator gem into system_tests group. 
master_manipulator has been heavily used  for master/agent sync tests. It should be in Gemfile of each module that needs integration test.

(FM-3923) Add puppetlabs-motd module to modulesync

---

config_defaults.yml
moduleroot/Rakefile

This updates modules to pull in puppet-blacksmith. This PR opens up modules to utilize the automation submitted in https://github.com/puppet-community/puppet-blacksmith/pull/26 which is a step in deprecating https://github.com/puppetlabs/qe-module-ci-helpers.

(maint) Use blacksmith for promotions

---

config_defaults.yml
moduleroot/Gemfile
moduleroot/Rakefile

This pulls in beaker-hostgenerator and adds a new rake task
`gen_nodeset` for utilizing it. The output of the rake task on success
is the location of the generated nodeset for use when calling Beaker
later on.
Example workflow:
```
export BEAKER_nodeset=`bundle exec rake gen_nodeset`
bundle exec rake beaker
```

(maint) Use beaker-hostgenerator to create nodesets

---

moduleroot/appveyor.yml

The current regular expression will skip any commit message that
contains the phrase Acceptance Test.  This can cause AppVeyor to skip
commits that are updating an acceptance test which is not a desired
behaviour.  Instead contributors should use the [skip ci] text to
skip AppVeyor builds.  This commit changes the regular expression to
only skip (doc) related commits.

(maint) Modify AppVeyor skip commit message

---

moduleroot/appveyor.yml

This commit removes a typo in the skip commit regular expression.  It had an
opening bracket which is not required.

(maint) Fix typo in appveyor regex

---

moduleroot/Gemfile

Similar to Facter for Puppet versions less than 3.5.0,
if Hiera version hasn't been set, use a version that
was released with older Puppet versions.
Additionally ensure that both facter and hiera are
treated this way no matter if Puppet is on Windows
or on *nix.

(MODULES-3200) Set Hiera and Facter versions for older puppet gems

---

config_defaults.yml
moduleroot/MAINTAINERS.md

All Puppet projects should contain a Maintenance section as either inside
README or in a separate file called MAINTAINERS.md.  This commit adds the
default modsync to create a MAINTAINERS.md file.  A file was used instead
of updating README as it is much easier to managae and automate the entire
content of the file instead of a section within a README, which is unique per
module.
The default of the Forge Modules mailing address is used, but can be modified
on a per module basis.
Example file from ACL module;
``` markdown
Maintainers:
- Puppet Forge Modules Team `forge-modules |at| puppet |dot| com`
Tickets: https://tickets.puppet.com/browse/MODULES. Make sure to set component to `acl`.
```

(FM-5165) Add MAINTAINERS.md file to all modules

---

.gitignore
config_defaults.yml
moduleroot/.travis.yml
moduleroot/Gemfile
moduleroot/LICENSE

The modsync moduleroot files required modification as they did not provide
the required configuration parameters for Windows modules.
- Added the ability for Apache2 and Puppet PE licensing per module.  Apache 2
is the default if not specified
- Added 'allow_failures' to Travis CI config.  This is a BAD practice and
should not be used, however it can be used temporarily to allow PR CIs to
continue if needs be
- Added the ability to specify a 'ref' for a git based gem in the Gemfile
Housekeeping
- Added gemfile.local to gitignore

(maint) Update modsync root files after audit

---

moduleroot/.gitignore
moduleroot/CONTRIBUTING.md

Added the directory tmp to the gitigore list.  It seems to have been
missing in error.  The CONTRIBUTING.MD file was updated by changing
puppetlabs to puppet after the company change.

(maint) Update CONTRIBUTING.md and gitignore

---

moduleroot/Gemfile

The Win32-Service gem was updated to 0.8.9 however the new gem pulled in a
dependant gem called ffi-win32-extensions which has a name collision on the
FFI:Pointer.read_wide_string method.  This causes Puppet to fail in mutiple
locations.
This commit sets the maximum version of the win32-xxxx gems the same as puppet
does in https://github.com/puppetlabs/puppet/master/ext/project_data.yaml#L49-L54

(FM-5240) Set maximum version on win32-xxx gems

---

config_defaults.yml

Changing the config option back to 140 char, because the disable_char_check one doesn't exist and was a flaw in the docs.
/cc @tphoney

(maint) Disable 140char lint check.

---

.travis.yml
moduleroot/Gemfile

An update to FFI (1.9.11) has caused downstream gems to error due to a bug
introduced in 1.9.11.  FFI Github issue 506 (ffi/ffi#506)
shows this is affecting other users of FFI as well.  This commit pins FFI to the
latest known good working version of 1.9.10.  This change will be reverted in the
future once issue 506 is resolved.

(PUP-6473) Pin FFI to 1.9.10

---

moduleroot/Gemfile

The commit 99efa61397653903cee4f81592c3d8f70bfd34e5 restricted the FFI
version however the minimum version of 1.9.6 was too low for older
Puppet Gem versions (3.7).  This commit changes the FFI version specification
to purley a maximum version restriction.  Without this commit CI PR tests
against older Puppet versions will fail.

(PUP-6473) Relax FFI version pin to only specify maximum version

---

moduleroot/Gemfile

The FFI issue has been resolved and released as 1.9.13
This reverts commit 6ef868e.
This reverts commit 83d2887.

(PUP-6477) Revert changes made in PUP-6473

---

moduleroot/Gemfile

See MODULES-3640 for more context. tldr; json_pure as of 2.0.2 requires ruby 2 - because Puppet tests against many different versions of ruby, including 1.9.3, we need to ensure we can still get json_pure. The original json_pure dependency is expressed by puppetlabs/puppet (unversioned).
Signed-off-by: Moses Mendoza <mendoza.moses@gmail.com>

(MODULES-3640) Add json_pure requirement

---

moduleroot/Gemfile

- Version 0.8.7 of the win32-service gem had a bug that prevented it
from properly retrieving all services on Windows 10 with the
Win32::Service.services call.
In particular, the services pvhdparser and vhdparser don't have
delayed start info, which would previously cause errors.
This is fixed in the 0.8.8 version of the gem
- This is required for PUP 4.6.0 and above

(PUP-6459) Update win32-service to 0.8.8

---

config_defaults.yml

This commit adds Ruby 2.3 versions to test against via Travis and AppVeyor, in
anticipation of supporting this ruby version in an upcoming version of Puppet.

(MODULES-3775) Add Ruby 2.3 to appveyor and travis

---

moduleroot/Gemfile

- Only Puppet 3.6.z and lower requires sys-admin gem, which was removed
for Puppet 3.7.0+.  Since that version only requires on at most Ruby
1.9.3, restrict its installation there.
Otherwise, running from a file:/// source for local Puppet with Ruby
2.3 on Windows will fail to perform a `bundle install`
sys-admin was removed officially in:
https://github.com/puppetlabs/puppet/commit/480f0362dde3ad52045ed026bafdc13ac6686174

(maint) Restrict sys-admin gem to Ruby 1.x

---

config_defaults.yml

This PR pins parallel_tests version depending on the Ruby version. Also included is a Mocha workaround.

Pinning parallel_tests versions to Ruby versions and including mocha workaround

---

config_defaults.yml
moduleroot/Gemfile

As per https://github.com/jonnytdevops/puppetlabs-firewall/commit/c1b0e7b46b8277d41c75e50465908d4cbc3f3267

Workaround frozen strings on ruby 1.9

---

moduleroot/.gitignore

for the Jenkins "release to forge" jorb. 
the blacksmith job that Jenkins runs looks to .gitignore for files to exclude from the module tarball. Since Jenkins also installs all dependencies in vendor/, if it's not in the gitignore it will cause the job to fail because the tarball will be too big

add vendor/ to gitignore

---

config_defaults.yml

This finally concludes our quest to automate all of our low-priority release
checks.
It also needs to wait for the PRs referenced in FM-5800 to be merged.

(FM-5800) Update travis to use release_checks

---

config_defaults.yml

The plan is to onboard every module to use the beaker-module_install_helper library and from there extend its functionality in the future. Therefore I have added it to the Gemfile of all repositories to save doing this individually in the future.

[MODULES-4224] Add beaker-module_install_helper to all modules gemfiles

---

moduleroot/.gitignore

As we move towards using strings to document our modules, there
will be files YARD generates that we don't want to commit to the
module repo. Update the default gitignore for modulesync so that
it includes these files.

(MODULES-4272) Update .gitignore for strings

---

.travis.yml

Previously, the Travis CI command used to verify the modsync configurations was
modified to exclue the vsphere and sqlserver modules in commit 3012627.
However the command was escaping text which did not need to be, thus the command
was failing to exclude those modules.  This commit removes the escaping and
ensures that the vsphere and sqlserver module are not checked during a Travis CI
run. These modules are excluded as they are private Github repos.

(maint) Fix Travis msync invocation

---

config_defaults.yml
managed_modules.yml

This commit adds the puppetlabs-puppet_agent module as a managed module.
This PR builds on https://github.com/puppetlabs/modulesync_configs/pull/128

(maint) Add puppetlabs-puppet_agent as a managed module

---

config_defaults.yml
moduleroot/locales/config.yaml

All modules now need to have a locales/ directory that contains a config.yaml for i18n tasks and storing translations (pot and po files). This adds the locales directory and the config.yaml inside it as well as the configurable values in config_defaults. At a later point there will also be a directory for translated readmes.

(MODULES-4375) add locales directory and config.yaml

---

moduleroot/spec/spec_helper.rb

With release of Puppet 4.10.0 using Puppet.version.to_f will return 4.1 which will cause issues with multiple test suites. This change uses Puppet's versioncmp function to do the comparison instead.

[MODULES-4528] Replace Puppet.version.to_f with versioncmp function

---

config_defaults.yml
moduleroot/locales/config.yaml

metadata.json should not be in the source files array, as it is being managed separately now, which was my fault so this removes that and adds a newline to the end of the config.yaml template.

(maint) locales/config adjustments

---

config_defaults.yml
moduleroot/Gemfile

This involves removing a number of gems from the development and system_tests groups in the Gemfile config that have been abstracted out to puppet-module-gems and referencing just the puppet-module-gems themselves.
This is an attempt to reduce the need to run msync every time we have a dependency conflict, by simply updating the puppet-module-gems generated gems on rubygems to fix the dependency issues.

[MODULES-4506] Implement puppet-module-gems

---

.travis.yml
config_defaults.yml
managed_modules.yml

we are welcoming the redhat satellite module into the modulesync family, yay. this adds it to both managed_modules and config_defaults (as a linux only module).

(MODULES-4511) add satellite_pe_tools to modulesync

---

config_defaults.yml
managed_modules.yml

Previously the puppetlabs-windows module was not under modsync control.  This
commit adds the module so that module publishing can be automated.

(maint) Add puppetlabs-windows to modsync

---

config_defaults.yml
managed_modules.yml

Previously the netscaler module was not modsync which is now causing CI failures
due to missing gems.  This commit will permanently add netscaler under modsync
control.

(MODULES-5013) Update netscaler module with modsync

---

config_defaults.yml

Puppet platform 5.0.0 release is upon us so we need to update ruby and puppet versions in our travis configs. This adds a ruby 2.4.0/puppet 5 cell and updates ruby 2.1.7 to ruby 2.1.9 because that's the 2.1.x that the agent ships with.

(MODULES-5139) bump travis matrix versions

---

config_defaults.yml
moduleroot/appveyor.yml

Puppet platform 5.0.0 release is upon us so we need to update ruby and puppet versions in our appveyor configs. This updates 23 and 23-x64 to 24 and 24-x64 as well as updating the oldest supported puppet version to 4.7.0

(MODULES-5140) bump appveyor matrix versions

---

config_defaults.yml

In order to start auto generating our changelogs we need all
modules to have the github_changelog_generator gem. Since we're
still waiting on a fix to be merged into the upstream version of the
gem, we're relying on David's fork which is being maintained with that
fix for the PDK.

(MODULES-5291) Add github_changelog_generator gem

---

config_defaults.yml
managed_modules.yml

We've given the rabbitmq to Vox Pupuli so we shouldn't manage it
with our modulesync configs anymore.

(maint) Stop managing rabbitmq

---

config_defaults.yml

- Version 0.0.8 is causing problems inside Puppet Jenkins
infrastructure due to the introduction of rspec-puppet-facts which
depends transitively on json. Json is not satisfied with the gem
included with Ruby, and thus attempts are made to compile native
extensions where no compiler is available.
- Version 0.0.9 and 0.0.10 include a newer version of
metadata-json-lint (2.0.1) which depends on Puppet >= 4.7.0
which hasn't yet been set to the minimum version across all
pipeline definitions. For instance, Puppet is still running
version 4.2.3 in some matrices.

(MODULES-5303) 0.0.7 pin puppet-module-win-dev-rXX

---

config_defaults.yml

This reverts commit c5ae7d0784a2718670521a2fc47de3b9a23afbc6.  This gem depends
on activesupport which requires Ruby 2.2 or above, which is incompatible with
Puppet testing which is on Ruby 2.1.9.

Revert "(MODULES-5291) Add github_changelog_generator gem"

---

config_defaults.yml

This adds CONTRIBUTING.md to the config_defaults file so it is updated along with everything else. Also, since we're on the eve of releasing full i18n, I've updated the locales/config.yml with a generic 'source_files' glob.

(maint) adds contributing.md and updates source files for i18n

---

config_defaults.yml

This patch aligns the version of ruby for testing Puppet 5 with the supported version.
https://docs.puppet.com/puppet/5.0/about_agent.html

Use the correct ruby version (2.4.1) that corresponds with Puppet 5

---

config_defaults.yml

Currently java-ks is only listed as a Linux module. It is actually
cross-platform therefore adding Windows to it. This will allow java_ks
to make use of files such as appveyor.yml

(maint) - Adding java_ks to be managed as a Windows module

---

config_defaults.yml
managed_modules.yml

Removing this module from our modulesync as it has been migrated to
voxpupuli.

 (maint) - Removing mongodb

---

README.md
moduleroot/.travis.yml.erb

Adds an option for an `env` section in the `.travis.yml` configuration,
to provide either `global` or `matrix` environment settings, per
https://docs.travis-ci.com/user/environment-variables/#Global-Variables

MODULES-6103: Add `env` section to `.travis.yml` template

---

moduleroot/Gemfile.erb

Since a few days the minitar < 0.6 dependency is being flagged by github's
vulnerability scanner, we remove it now, and drop final pretences at
supporting puppet 3.
Additionally there is some complexity around which specific versions of
the win32 gems to use with puppet 4 < 4.5.2. Since none of those puppet
versions are supported, this summarily drops the workarounds for that
too.

(FM-6588) Remove workarounds for puppet < 4.5.2

---

moduleroot/appveyor.yml.erb

- The fix in place here was temporary due to AppVeyor having available
an older Ruby 2.4 that shipped a buggy OpenSSL with a race condition.
Without the upgrade, installing large gemsets would intermittenly
fail.
* Original RubyInstaller discussion at:
https://github.com/oneclick/rubyinstaller2/issues/68
* Ruby bug is documented at https://bugs.ruby-lang.org/issues/11033
* OpenSSL 2.0.4 contains the patch as of 8/8/2017
https://github.com/ruby/ruby/commit/b08e0ade5baacbc7d4754e9f6afe8d09a3e00bc5#diff-51a5e2412fcf851e37d1883b1ae53de5
* RubyInstaller 2.4.2-2 picked up the fix and was released 9/15/2017
https://rubyinstaller.org/2017/09/15/rubyinstaller-2.4.2-2-released.html
* AppVeyor issue was filed
https://github.com/appveyor/ci/issues/1790
AppVeyor began shipping updated Ruby in their …

(maint) Remove AppVeyor OpenSSL update on Ruby 2.4

---

moduleroot/.travis.yml.erb

Prior to this commit the travis.yml template includes a before_install
step which upgrades bundler. This was done to solve for an issue where
Travis included the default version of bundler for each ruby version
in the matrix. Now, however, Travis seems to include the latest
compatible version of bundler - at this time, `1.16.0` - and we are
upgrading to `1.16.1` which has an incompatibility issue on Travis
at this time.
This commit removes the now-unneccessary update step and puts the
heavy lifting for maintaining a compatible matrix back onto Travis.
A downside to this is that we may have future breaks caused by Travis
mismanaging their images, but this is a risk we already have. An
alternative is to pin to a version ourselves and manage the pinned
version over time.

(MODULES-6339) Remove bundler update from before_install

---

moduleroot/Rakefile.erb

This rake task will only be added if .sync.yml of target projects specifies a Rakefile entry called `changelog_generator_since_tag`

(FM-6544) Add changelog generator

---

config_defaults.yml
managed_modules.yml

This commit adds the unsupported mount_iso module to be under modsync control.

(maint) Add mount_iso unsupported module

---

config_defaults.yml
managed_modules.yml

This is being removed from modulesync because it has been converted to
be PDK compliant. Changes will now be managed using pdk-templates.

(MODULES-6325) - Removal of vcsrepo

---

config_defaults.yml
managed_modules.yml

apt is being removed as it will recieve updates from pdk templates.

(MODULES-6452) - Remove apt from modulesync

---

config_defaults.yml
managed_modules.yml

This module is now compliant with the pdk. Updates will be pushed out via templates.

(MODULES-6457)- Remove haproxy from modulesync

---

config_defaults.yml
managed_modules.yml

This module has now been converted and is PDK compliant. Any required changes will be pushed out via the pdk templates.

(MODULES-6455) - Removing firewall from modulesync

---

config_defaults.yml
managed_modules.yml

This module has been converted and is now PDK compliant therefore is no longer needed in modulesync.

(MODULES-6462) - Removing exec from modulesync

---

config_defaults.yml
managed_modules.yml

- Undoes changes from f56e5875e1f308db10f623a5704c52e56c09cc68 as
puppetlabs-scheduled_task is a PDK module and should not be managed
with modulesync any longer.
- See https://github.com/puppetlabs/puppetlabs-scheduled_task/pull/14
https://tickets.puppetlabs.com/browse/MODULES-6591

(maint) Remove PDK managed scheduled_task module

---

config_defaults.yml
moduleroot/Rakefile.erb

This reverts commit ffe29d9c9809cb4427f6b0e87ad699736fed5119.
The git reference assumes a configured SSH agent for the git client.  This is a
new requirement for module development and breaks the more usual Windows
development workflows which do not depend on an SSH agent.  Also this will break
bundling on default configured git clients which only need read only access to
repositories, for example CI testing in Jenkins, Appveyor, Travis and the like.

Revert "(FM-6544) More changes for #174"

---

managed_modules.yml

This commit removes the reboot module as it has been converted to PDK.

(maint) Remove reboot module

---

README.md

Using modsync is now deprecated in favour of PDK.  This commit adds a warning to
the README so people are aware of the status of this project.

(maint) Add deprecation disclaimer
